### ISSUE TITLE
Wrong forcedPackageId for framework-ext-res.apk from MiUI7 android 4.4.2

### ISSUE THREAD

**Issue by Hikari-no-Tenshi** [iBotPeaches/Apktool#1220]
1. Apktool Version: 2.1.0-180728-SNAPSHOT.
2. Operating System: Windows.
3. APK From: MiUI7 android 4.4.2.

Decompiling APK with apktool writes wrong forcedPackageId to apktool.yml.
For framework-ext-res.apk it writes 16, but should be 17.

```
!!brut.androlib.meta.MetaInfo
apkFileName: framework-ext-res.apk
compressionType: false
doNotCompress:
- arsc
isFrameworkApk: true
packageInfo:
  forcedPackageId: '16'
  renameManifestPackage: com.miui.rom
sdkInfo: null
sharedLibrary: false
unknownFiles: {}
usesFramework:
  ids:
  - 1
  - 16
  tag: null
version: 2.1.0-180728-SNAPSHOT
versionInfo:
  versionCode: '1010000'
  versionName: 1.1.0.0
```

APK
[framework-ext-res.zip](https://github.com/iBotPeaches/Apktool/files/211822/framework-ext-res.zip)

Frameworks
[frameworks.zip](https://github.com/iBotPeaches/Apktool/files/211825/frameworks.zip)
