### ISSUE TITLE
sdkInfo: null in apktool.yml

### ISSUE THREAD

**Issue by derFunk** [iBotPeaches/Apktool#1327]
### Information
1. **Apktool Version (`apktool -version`)** - 2.2.0
2. **Operating System (Mac, Linux, Windows)** - Windows & OSX
3. **APK From? (Playstore, ROM, Other)** - Other / Local one
### Steps to Reproduce
1. `apktool  d myapp.apk`

When decompiling a local apk I have, sdkInfo is set to "null".
Only happens with my local apk, wasn't able to reproduce yet.

The original AndroidManifest.xml has `<uses-sdk android:minSdkVersion="18" targetSdkVersion="23"/>`, which doesn't reflect in the generated apktool.yml.

That's how the complete apktool.yml looks like:

```
!!brut.androlib.meta.MetaInfo
apkFileName: myapp.apk
compressionType: false
doNotCompress:
- arsc
- json
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo: null
sharedLibrary: false
unknownFiles: {}
usesFramework:
  ids:
  - 1
  tag: null
version: 2.2.0
versionInfo:
  versionCode: '656'
  versionName: 1.1.10938.656
```

Having `null` as sdkInfo leads to a generated AndroidManifest.xml when rebuilding the apk with `apktool b`, which produces problems.
